FROM oven/bun:1


WORKDIR  /usr/src/web


COPY  ./packages ./packages
COPY  ./bun.lock ./bun.lock

COPY  ./package.json  ./package.json
COPY  ./turbo.json     ./turbo.json

COPY ./apps/web ./apps/web


COPY . .


RUN bun install
RUN bun run db:generate
RUN bun run build




EXPOSE 8081

CMD [ "bun","run","start:web" ]