FROM oven/bun:1


WORKDIR  /usr/src/http-server

COPY  ./packages ./packages
COPY  ./bun.lock ./bun.lock

COPY  ./package.json  ./package.json
COPY  ./turbo.json     ./turbo.json

COPY ./apps/http-server  ./apps/http-server



COPY . .

RUN bun install
RUN bun run db:generate




EXPOSE 8080

CMD [ "bun","run","start:backend" ]